-- raxis/live-e2e/seed/postgres/01-seed.sql
--
-- Idempotent postgres seed for the extended e2e scenario
-- (`raxis/specs/v2/e2e-extended-scenario.md` §3.1).
--
-- Mounted into the postgres container at
-- `/docker-entrypoint-initdb.d/01-seed.sql` by
-- `live-e2e/docker-compose.extended.e2e.yml`. Postgres runs every
-- `*.sql` in this directory at first boot; the test harness's
-- preflight additionally re-applies it via `psql` so re-runs against
-- a preserved volume converge to the same state.
--
-- Determinism contract — the canonical expected output in
-- `live-e2e/seed/expected/postgres_rows.json` is generated by hand
-- from the same formula below. A drift between the script and the
-- expected JSON breaks the witness assertion in the test loudly.
-- Whoever changes one MUST regenerate the other in the same commit.
--
-- Schema:
--   id          TEXT PRIMARY KEY     -- "row-NNNN", NNNN zero-padded 0001..0025
--   payload     JSONB NOT NULL       -- canonical body (see below)
--   created_at  BIGINT NOT NULL      -- pinned 1700000000
--
-- Payload formula (per row, where i ∈ 1..25):
--   {
--     "index": i,
--     "label": "row-NNNN",
--     "magic": ((i * 2654435761) mod 2^32),  -- Knuth multiplicative hash
--     "tag":   ["alpha", "beta", "gamma"][(i - 1) mod 3]
--   }
--
-- The DB and user are provisioned by the docker-compose `environment`
-- block (POSTGRES_DB=raxis_e2e, POSTGRES_USER=raxis_test). This
-- script ALSO creates a logical sub-database `raxis_e2e_pg` so the
-- test's preflight URL (`postgresql://...:5432/raxis_e2e_pg`) lands
-- without touching the bootstrap DB.

\set ON_ERROR_STOP on

-- Create the test-scoped database if it doesn't exist. We can't use
-- CREATE DATABASE inside a transaction, so this runs against the
-- bootstrap DB before we connect to the target.
SELECT 'CREATE DATABASE raxis_e2e_pg'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'raxis_e2e_pg')
\gexec

-- Switch to the seeded database for the rest of the script.
\connect raxis_e2e_pg

CREATE TABLE IF NOT EXISTS seeded_rows (
    id          TEXT PRIMARY KEY,
    payload     JSONB NOT NULL,
    created_at  BIGINT NOT NULL
);

-- Knuth multiplicative hash, mod 2^32, in pure SQL.
-- Returns a deterministic 32-bit non-negative integer per index.
DO $$
DECLARE
    i INT;
    knuth_const BIGINT := 2654435761;
    magic_val   BIGINT;
    tag_val     TEXT;
    id_val      TEXT;
    payload_val JSONB;
BEGIN
    FOR i IN 1..25 LOOP
        magic_val := (i * knuth_const) % 4294967296;
        tag_val   := (ARRAY['alpha', 'beta', 'gamma'])[((i - 1) % 3) + 1];
        id_val    := 'row-' || lpad(i::text, 4, '0');
        payload_val := jsonb_build_object(
            'index', i,
            'label', id_val,
            'magic', magic_val,
            'tag',   tag_val
        );

        INSERT INTO seeded_rows (id, payload, created_at)
        VALUES (id_val, payload_val, 1700000000)
        ON CONFLICT (id) DO UPDATE
            SET payload    = EXCLUDED.payload,
                created_at = EXCLUDED.created_at;
    END LOOP;
END;
$$;

-- Sanity-check: count and exit non-zero (via \echo + RAISE) if the
-- final row count is not the expected 25. Helps the harness's
-- preflight surface a fixture-drift problem with one round-trip
-- instead of failing deeper in the test.
DO $$
DECLARE
    n INT;
BEGIN
    SELECT COUNT(*) INTO n FROM seeded_rows;
    IF n <> 25 THEN
        RAISE EXCEPTION 'seeded_rows expected 25 rows, found %', n;
    END IF;
END;
$$;
