// raxis-kernel::authority::verifier_token — Machine-issued verifier run tokens.
//
// Normative reference: kernel-core.md §2.3 `src/authority/verifier_token.rs`.
//
// Verifier run tokens are machine-to-machine credentials. The kernel issues
// them to authorise a verifier subprocess to call back with results. They are
// distinct from session tokens (process auth) and approval tokens (human auth).
//
// Token structure (stored in `verifier_run_tokens` table):
//   token_id:   UUID v4 (identifies the row)
//   run_id:     UUID — identifies the specific verifier run
//   token_hash: SHA-256 of the raw token bytes (hex, 64 chars)
//   expires_at: Unix seconds
//   consumed_at: NULL until consumed
//
// The raw token bytes are generated by raxis-crypto::token::generate_session_token
// (32 CSPRNG bytes → 64 hex chars). Only the SHA-256 hash is stored; the raw
// token is returned once to the caller (the kernel spawn path) and never stored.
// This is the "store-the-hash, not-the-secret" pattern.

use raxis_crypto::token::{generate_verifier_token, sha256_hex};
use raxis_store::{Store, Table};
use raxis_types::unix_now_secs;

use crate::authority::keys::AuthorityError;

const VRT: &str = Table::VerifierRunTokens.as_str();

/// Row-level binding carried by a validated verifier token. The
/// witness handler must compare these fields against the submitted
/// envelope before accepting evidence; a verifier token is scoped to
/// exactly one `(task_id, gate_type, evaluation_sha)` tuple.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidatedVerifierToken {
    pub verifier_run_id: String,
    pub task_id: String,
    pub gate_type: String,
    pub evaluation_sha: String,
}

/// Issue a new verifier run token for `run_id`.
///
/// Returns the raw token hex (64 chars). The kernel stores only the SHA-256
/// hash. DDL Table 12 requires task_id, gate_type, evaluation_sha columns;
/// the caller (verifier_runner.rs) supplies all three.
pub fn issue_verifier_token(
    run_id: &str,
    task_id: &str,
    gate_type: &str,
    evaluation_sha: &str,
    ttl_secs: u64,
    store: &Store,
) -> Result<String, AuthorityError> {
    // RNG failure aborts issuance; we never persist a verifier-run-token row
    // whose `token_hash` was derived from a degraded random source.
    let (raw_token, token_hash) = generate_verifier_token()?;
    let now = unix_now_secs();
    let expires_at = now + ttl_secs as i64;

    // DDL Table 12 PKs on verifier_run_id; issue_verifier_token receives run_id
    // from the caller (verifier_runner.rs) and uses it as the PK.
    let conn = store.lock_sync();
    conn.execute(
        &format!(
            "INSERT INTO {VRT}
                (verifier_run_id, task_id, gate_type, evaluation_sha,
                 token_hash, issued_at, expires_at, consumed)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 0)"
        ),
        rusqlite::params![
            run_id,
            task_id,
            gate_type,
            evaluation_sha,
            &token_hash,
            now,
            expires_at
        ],
    )
    .map_err(|e| AuthorityError::Store(raxis_store::StoreError::Rusqlite(e)))?;

    Ok(raw_token)
}

/// Validate a raw token presented by a verifier subprocess.
///
/// Hashes the raw token and looks up the matching row. Returns
/// `AuthorityError::TokenNotFound` if no row matches the hash, `TokenExpired`
/// if the row exists but has passed `expires_at`, `TokenConsumed` if already
/// consumed.
///
/// **Standalone wrapper** — the canonical witness commit path uses
/// `validate_verifier_token_in_tx` so the validate, witness write, and
/// consume all run inside one transaction (`kernel-store.md`
/// §2.5.1.1 Pattern C). Pre-fix, splitting validate and consume across
/// two mutex acquisitions opened a window where a concurrent
/// `recovery::reconcile_tasks` could expire the token between validate and
/// consume, leaving a witness row that the kernel told its producer was
/// rejected.
///
/// Does NOT consume the token — see `consume_verifier_token`.
pub fn validate_verifier_token(raw_token: &str, store: &Store) -> Result<String, AuthorityError> {
    let conn = store.lock_sync();
    validate_verifier_token_in_tx(&conn, raw_token)
}

/// Validate a raw token inside an existing transaction.
///
/// **INV-STORE-02 (kernel-store.md §2.5.1.1 Pattern C):** the witness
/// handler runs validate → witness-write → consume in one
/// `conn.transaction()` so the three steps are atomic against a
/// concurrent token expiry sweep.
pub fn validate_verifier_token_in_tx(
    conn: &rusqlite::Connection,
    raw_token: &str,
) -> Result<String, AuthorityError> {
    validate_verifier_token_row_in_tx(conn, raw_token).map(|row| row.verifier_run_id)
}

/// Validate a raw token and return the row binding minted with it.
///
/// This is the preferred witness-intake API. The token is a bearer
/// credential, but it is not a free-floating capability: the kernel
/// minted it for one verifier run over one task/gate/evaluation. Callers
/// must reject submissions whose envelope does not match this row.
pub fn validate_verifier_token_row_in_tx(
    conn: &rusqlite::Connection,
    raw_token: &str,
) -> Result<ValidatedVerifierToken, AuthorityError> {
    // Reject malformed hex up-front rather than collapsing to an empty buffer
    // (which would let a presented token of "" hash to the SHA-256 of empty
    // and accidentally match a malformed row). On any decode error we return
    // `TokenMismatch` — the verifier presented something that is not a token.
    let raw_bytes = hex::decode(raw_token).map_err(|_| AuthorityError::TokenMismatch)?;
    let token_hash = sha256_hex(&raw_bytes);
    let now = unix_now_secs();

    let (run_id, task_id, gate_type, evaluation_sha, expires_at, consumed): (
        String,
        String,
        String,
        String,
        i64,
        i64,
    ) = conn
        .query_row(
            &format!(
                "SELECT verifier_run_id, task_id, gate_type, evaluation_sha, expires_at, consumed
                   FROM {VRT}
                  WHERE token_hash=?1"
            ),
            rusqlite::params![&token_hash],
            |r| {
                Ok((
                    r.get(0)?,
                    r.get(1)?,
                    r.get(2)?,
                    r.get(3)?,
                    r.get(4)?,
                    r.get(5)?,
                ))
            },
        )
        .map_err(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => AuthorityError::TokenNotFound,
            other => AuthorityError::Store(raxis_store::StoreError::Rusqlite(other)),
        })?;

    if consumed != 0 {
        return Err(AuthorityError::TokenConsumed);
    }
    if expires_at <= now {
        return Err(AuthorityError::TokenExpired);
    }

    Ok(ValidatedVerifierToken {
        verifier_run_id: run_id,
        task_id,
        gate_type,
        evaluation_sha,
    })
}

/// Consume a verifier token — set `consumed_at = now()`.
///
/// Once consumed, `validate_verifier_token` returns `TokenConsumed` for any
/// subsequent presentation. Tokens are single-use.
///
/// **Standalone wrapper** — the canonical witness commit path uses
/// `consume_verifier_token_in_tx` so consume composes atomically with
/// validate and witness-write in one transaction.
pub fn consume_verifier_token(raw_token: &str, store: &Store) -> Result<(), AuthorityError> {
    let conn = store.lock_sync();
    consume_verifier_token_in_tx(&conn, raw_token)
}

/// Consume a verifier token inside an existing transaction.
///
/// **INV-STORE-02 (kernel-store.md §2.5.1.1 Pattern C):** if this returns
/// `TokenConsumed` (UPDATE found 0 rows) the caller MUST roll back its
/// transaction so the witness INSERT does not commit. The witness handler
/// relies on this: a failed consume rolls back the entire `conn.transaction()`,
/// undoing the just-inserted `witness_records` row so the gate evaluator
/// never sees a witness whose producer received a rejection reply.
pub fn consume_verifier_token_in_tx(
    conn: &rusqlite::Connection,
    raw_token: &str,
) -> Result<(), AuthorityError> {
    let raw_bytes = hex::decode(raw_token).map_err(|_| AuthorityError::TokenMismatch)?;
    let token_hash = sha256_hex(&raw_bytes);
    let now = unix_now_secs();

    let rows = conn
        .execute(
            &format!(
                "UPDATE {VRT} SET consumed=1, consumed_at=?1 WHERE token_hash=?2 AND consumed=0"
            ),
            rusqlite::params![now, &token_hash],
        )
        .map_err(|e| AuthorityError::Store(raxis_store::StoreError::Rusqlite(e)))?;

    if rows == 0 {
        Err(AuthorityError::TokenConsumed)
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn seed_token_task(store: &Store, task_id: &str) {
        let conn = store.lock_sync();
        let initiatives = Table::Initiatives.as_str();
        let tasks = Table::Tasks.as_str();
        conn.execute(
            &format!(
                "INSERT OR IGNORE INTO {initiatives}
                    (initiative_id, state, terminal_criteria_json,
                     plan_artifact_sha256, created_at)
                 VALUES ('init-verifier-token-tests', 'Executing', '{{}}', 'sha', 1)"
            ),
            [],
        )
        .unwrap();
        conn.execute(
            &format!(
                "INSERT INTO {tasks}
                    (task_id, initiative_id, lane_id, state, actor,
                     policy_epoch, admitted_at, transitioned_at)
                 VALUES (?1, 'init-verifier-token-tests', 'default',
                         'GatesPending', 'kernel', 1, 1, 1)"
            ),
            rusqlite::params![task_id],
        )
        .unwrap();
    }

    #[test]
    fn validate_row_returns_task_gate_and_evaluation_binding() {
        let store = Store::open_in_memory().unwrap();
        seed_token_task(&store, "task-bind");
        let raw = issue_verifier_token("run-bind", "task-bind", "coverage", "abc123", 60, &store)
            .unwrap();

        let conn = store.lock_sync();
        let row = validate_verifier_token_row_in_tx(&conn, &raw).unwrap();
        assert_eq!(
            row,
            ValidatedVerifierToken {
                verifier_run_id: "run-bind".to_owned(),
                task_id: "task-bind".to_owned(),
                gate_type: "coverage".to_owned(),
                evaluation_sha: "abc123".to_owned(),
            }
        );
    }

    #[test]
    fn token_expiring_at_current_second_is_expired() {
        let store = Store::open_in_memory().unwrap();
        seed_token_task(&store, "task-now");
        let raw =
            issue_verifier_token("run-now", "task-now", "tests", "sha-now", 60, &store).unwrap();
        {
            let conn = store.lock_sync();
            conn.execute(
                &format!("UPDATE {VRT} SET expires_at = ?1 WHERE verifier_run_id = 'run-now'"),
                rusqlite::params![unix_now_secs()],
            )
            .unwrap();
        }

        let conn = store.lock_sync();
        let err = validate_verifier_token_row_in_tx(&conn, &raw).unwrap_err();
        assert!(matches!(err, AuthorityError::TokenExpired));
    }
}
