// raxis-cli::commands::policy — policy sign subcommand.
//
// Normative reference: cli-ceremony.md §4.1 `policy sign`.
//
// Signs a TOML artifact (policy.toml or plan.toml) with the operator's
// private key and writes <artifact>.sig. No kernel connection required.

use std::fs;
use std::path::PathBuf;

use crate::errors::CliError;
use crate::GlobalFlags;

pub fn run_sign(flags: &GlobalFlags, args: &[String]) -> Result<(), CliError> {
    let mut artifact_path: Option<PathBuf> = None;
    let mut key_path: Option<PathBuf> = None;
    let mut i = 0;

    while i < args.len() {
        match args[i].as_str() {
            "--key" => {
                i += 1;
                key_path = Some(PathBuf::from(
                    args.get(i)
                        .ok_or_else(|| CliError::Usage("--key requires a path".to_owned()))?,
                ));
            }
            arg if !arg.starts_with('-') && artifact_path.is_none() => {
                artifact_path = Some(PathBuf::from(arg));
            }
            other => return Err(CliError::Usage(format!("unknown policy sign flag: {other:?}"))),
        }
        i += 1;
    }

    let artifact_path = artifact_path
        .ok_or_else(|| CliError::Usage("policy sign requires <artifact.toml>".to_owned()))?;
    let key_path = key_path
        .or_else(|| flags.operator_key_path.clone())
        .ok_or_else(|| {
            CliError::Usage(
                "policy sign requires --key <path> or --operator-key global flag".to_owned(),
            )
        })?;

    // Read artifact bytes verbatim.
    let artifact_bytes = fs::read(&artifact_path).map_err(|e| CliError::Io {
        path: artifact_path.display().to_string(),
        source: e,
    })?;

    // Compute SHA-256 of file bytes.
    let sha256 = raxis_crypto::token::sha256_hex(&artifact_bytes);

    // Sign the SHA-256 digest with the operator's private key.
    let signing_key = crate::signing::load_operator_key(&key_path)?;
    let sig_hex = crate::signing::sign_bytes(&signing_key, sha256.as_bytes());

    // Compute operator fingerprint.
    let pubkey_bytes = signing_key.verifying_key().to_bytes();
    let fingerprint = crate::conn::pubkey_fingerprint(&pubkey_bytes);

    // Write <artifact>.sig in TOML format.
    let sig_path = artifact_path.with_extension("sig");
    let sig_toml = format!(
        r#"# RAXIS artifact signature — generated by `raxis-cli policy sign`
signed_by      = "{fingerprint}"
plan_sha256    = "{sha256}"
signature_hex  = "{sig_hex}"
signed_at      = {signed_at}
"#,
        signed_at = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs(),
    );
    fs::write(&sig_path, sig_toml.as_bytes()).map_err(|e| CliError::Io {
        path: sig_path.display().to_string(),
        source: e,
    })?;

    println!("✓ Signed {} → {}", artifact_path.display(), sig_path.display());
    println!("  fingerprint:  {fingerprint}");
    println!("  plan_sha256:  {sha256}");

    Ok(())
}
