// raxis-cli::commands::policy — policy sign subcommand.
//
// Normative reference: cli-ceremony.md §4.1 `policy sign` and kernel-store.md
// §2.5.3 "Plan artifact signing contract".
//
// Signs a TOML artifact (policy.toml or plan.toml) with the operator's
// private key and writes <artifact>.sig. No kernel connection required.
//
// Canonical signing scheme (the ONLY scheme accepted by the kernel):
//
//   signing_input = SHA-256("RAXIS-V1-PLAN" || 0x00 || artifact_bytes)
//   sig           = Ed25519Sign(operator_sk, signing_input)
//
// This routes through `raxis_crypto::plan::plan_signing_input` so that the
// CLI signer and the kernel verifier (`raxis_crypto::plan::verify_plan_signature`,
// called from `lifecycle::approve_plan`) agree on the byte-exact input. The
// previous implementation signed `sha256_hex(bytes).as_bytes()` (the UTF-8
// hex *string* of the digest) — review §2.2 catastrophic finding "plan
// signing semantic mismatch". No legacy operator key in the wild has yet
// signed real bundles under that scheme; we switch outright rather than
// carrying a compatibility branch.

use std::fs;
use std::path::PathBuf;

use raxis_crypto::plan::{plan_artifact_sha256, plan_signing_input};

use crate::errors::CliError;
use crate::GlobalFlags;

pub fn run_sign(flags: &GlobalFlags, args: &[String]) -> Result<(), CliError> {
    let mut artifact_path: Option<PathBuf> = None;
    let mut key_path: Option<PathBuf> = None;
    let mut i = 0;

    while i < args.len() {
        match args[i].as_str() {
            "--key" => {
                i += 1;
                key_path = Some(PathBuf::from(
                    args.get(i)
                        .ok_or_else(|| CliError::Usage("--key requires a path".to_owned()))?,
                ));
            }
            arg if !arg.starts_with('-') && artifact_path.is_none() => {
                artifact_path = Some(PathBuf::from(arg));
            }
            other => return Err(CliError::Usage(format!("unknown policy sign flag: {other:?}"))),
        }
        i += 1;
    }

    let artifact_path = artifact_path
        .ok_or_else(|| CliError::Usage("policy sign requires <artifact.toml>".to_owned()))?;
    let key_path = key_path
        .or_else(|| flags.operator_key_path.clone())
        .ok_or_else(|| {
            CliError::Usage(
                "policy sign requires --key <path> or --operator-key global flag".to_owned(),
            )
        })?;

    // Read artifact bytes verbatim. Whitespace, BOM, trailing newline — the
    // signature is over the file as it sits on disk; the kernel will hash and
    // verify the same exact bytes.
    let artifact_bytes = fs::read(&artifact_path).map_err(|e| CliError::Io {
        path: artifact_path.display().to_string(),
        source: e,
    })?;

    // Plain SHA-256 of the bytes (for `plan_sha256` field — surfaces in the
    // kernel's `signed_plan_artifacts.plan_bytes` and audit records).
    let sha256 = plan_artifact_sha256(&artifact_bytes);

    // Sign the canonical 32-byte SHA-256 of "RAXIS-V1-PLAN\x00" || artifact_bytes.
    // See module header — this MUST match what the kernel passes to
    // `Ed25519::verify` in `lifecycle::approve_plan`.
    let signing_key = crate::signing::load_operator_key(&key_path)?;
    let signing_input = plan_signing_input(&artifact_bytes);
    let sig_hex = crate::signing::sign_bytes(&signing_key, &signing_input);

    // Compute operator fingerprint.
    let pubkey_bytes = signing_key.verifying_key().to_bytes();
    let fingerprint = crate::conn::pubkey_fingerprint(&pubkey_bytes);

    // Write <artifact>.sig in TOML format.
    let sig_path = artifact_path.with_extension("sig");
    let sig_toml = format!(
        r#"# RAXIS artifact signature — generated by `raxis policy sign`
signed_by      = "{fingerprint}"
plan_sha256    = "{sha256}"
signature_hex  = "{sig_hex}"
signed_at      = {signed_at}
"#,
        signed_at = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs(),
    );
    fs::write(&sig_path, sig_toml.as_bytes()).map_err(|e| CliError::Io {
        path: sig_path.display().to_string(),
        source: e,
    })?;

    println!("✓ Signed {} → {}", artifact_path.display(), sig_path.display());
    println!("  fingerprint:  {fingerprint}");
    println!("  plan_sha256:  {sha256}");

    Ok(())
}
