// raxis-cli::commands::policy — policy sign / generate-sidecar-secret subcommands.
//
// Normative reference: cli-ceremony.md §4.1 `policy sign` and kernel-store.md
// §2.5.3 "Plan artifact signing contract".
//
// Signs a TOML artifact (policy.toml or plan.toml) with the operator's
// private key and writes <artifact>.sig. No kernel connection required.
//
// Canonical signing scheme (the ONLY scheme accepted by the kernel):
//
//   signing_input = SHA-256("RAXIS-V1-PLAN" || 0x00 || artifact_bytes)
//   sig           = Ed25519Sign(operator_sk, signing_input)
//
// This routes through `raxis_crypto::plan::plan_signing_input` so that the
// CLI signer and the kernel verifier (`raxis_crypto::plan::verify_plan_signature`,
// called from `lifecycle::approve_plan`) agree on the byte-exact input. The
// previous implementation signed `sha256_hex(bytes).as_bytes()` (the UTF-8
// hex *string* of the digest) — review §2.2 catastrophic finding "plan
// signing semantic mismatch". No legacy operator key in the wild has yet
// signed real bundles under that scheme; we switch outright rather than
// carrying a compatibility branch.

use std::fs;
use std::path::PathBuf;

use raxis_crypto::plan::{plan_artifact_sha256, plan_signing_input};
use raxis_crypto::token::try_random_array;

use crate::errors::CliError;
use crate::GlobalFlags;

// ---------------------------------------------------------------------------
// `raxis policy generate-sidecar-secret` — V2_GAPS §C5 / extensibility-traits.md §9A.7C.
//
// Mints a 32-byte cryptographically-random shared secret for the
// HTTP-sidecar HMAC-SHA256 authentication scheme and prints it as
// 64 hex characters. The secret is **never** persisted to disk by
// this command — the operator copies it into both
//
//   1. `policy.toml` under the matching `[[providers]]` block as
//      `sidecar_hmac_secret = "<64-hex>"`, and
//   2. the sidecar process's environment, e.g.
//      `export RAXIS_SIDECAR_HMAC_SECRET="<64-hex>"`.
//
// Output format:
//
//   * Default: a single line of 64 hex characters followed by `\n`.
//     Pipe-friendly: `raxis policy generate-sidecar-secret > secret.hex`.
//   * `--json`: a single-line JSON object
//     `{"sidecar_hmac_secret":"<64-hex>"}` for tooling that already
//     parses doctor output as JSON.
//   * `--annotated` (mutually exclusive with `--json`): three-line
//     human-readable form with the literal `sidecar_hmac_secret` key
//     and a fingerprint of the secret (first 8 hex of SHA-256, so
//     operators can disambiguate which secret got copied where) for
//     paste-into-`policy.toml` ergonomics.
//
// We deliberately do NOT persist anywhere by default: the only place
// the kernel ever needs the secret is via `policy.toml`, which is
// the operator-signed source of truth. Auto-writing into
// `policy.toml` would (a) require operator re-signing the bundle
// before the next epoch-advance and (b) silently mutate a file that
// must round-trip through `git diff` for audit. The operator
// workflow per `extensibility-traits.md §9A.7C` is paste-driven.
// ---------------------------------------------------------------------------

pub fn run_generate_sidecar_secret(
    _flags: &GlobalFlags,
    args: &[String],
) -> Result<(), CliError> {
    let mut json = false;
    let mut annotated = false;

    for a in args {
        match a.as_str() {
            "--json" => json = true,
            "--annotated" => annotated = true,
            other => {
                return Err(CliError::Usage(format!(
                    "unknown `policy generate-sidecar-secret` flag: {other:?} \
                     (available: --json, --annotated)"
                )))
            }
        }
    }
    if json && annotated {
        return Err(CliError::Usage(
            "--json and --annotated are mutually exclusive".to_owned(),
        ));
    }

    let bytes: [u8; 32] = try_random_array()?;
    let hex_secret = hex_encode(&bytes);

    if json {
        println!("{{\"sidecar_hmac_secret\":\"{hex_secret}\"}}");
    } else if annotated {
        let fp = sidecar_secret_fingerprint(&hex_secret);
        println!("# Generated by `raxis policy generate-sidecar-secret`.");
        println!("# Fingerprint (first 8 hex of SHA-256): {fp}");
        println!("# Paste under the matching [[providers]] block in policy.toml,");
        println!("# then re-sign with `raxis policy sign policy.toml`.");
        println!("# Set the same value in the sidecar's RAXIS_SIDECAR_HMAC_SECRET env.");
        println!("sidecar_hmac_secret = \"{hex_secret}\"");
    } else {
        println!("{hex_secret}");
    }
    Ok(())
}

/// 64-character lowercase hex encoding without external deps. The
/// `hex` crate is already a workspace dep but we emit through this
/// trivial helper to keep `run_generate_sidecar_secret` self-contained.
fn hex_encode(bytes: &[u8]) -> String {
    const TBL: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(TBL[(b >> 4) as usize] as char);
        out.push(TBL[(b & 0x0f) as usize] as char);
    }
    out
}

/// First 8 lowercase hex chars of SHA-256(secret_bytes_as_hex_ascii).
/// Lets operators eyeball whether the secret they pasted into
/// `policy.toml` matches the one configured in the sidecar without
/// printing the secret itself.
fn sidecar_secret_fingerprint(hex_secret: &str) -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(hex_secret.as_bytes());
    let digest = h.finalize();
    let mut fp = String::with_capacity(8);
    const TBL: &[u8; 16] = b"0123456789abcdef";
    for b in &digest[..4] {
        fp.push(TBL[(b >> 4) as usize] as char);
        fp.push(TBL[(b & 0x0f) as usize] as char);
    }
    fp
}

pub fn run_sign(flags: &GlobalFlags, args: &[String]) -> Result<(), CliError> {
    let mut artifact_path: Option<PathBuf> = None;
    let mut key_path: Option<PathBuf> = None;
    let mut force_misconfig: bool = false;
    let mut i = 0;

    while i < args.len() {
        match args[i].as_str() {
            "--key" => {
                i += 1;
                key_path = Some(PathBuf::from(
                    args.get(i)
                        .ok_or_else(|| CliError::Usage("--key requires a path".to_owned()))?,
                ));
            }
            // Per cli-ceremony.md §4.1 `policy sign --force-misconfig`:
            // operator-explicit acknowledgement that the artifact contains
            // operator entries with `force_misconfig_bypass = true`. Without
            // this flag, signing such an artifact is refused — the bypass
            // must be visible in shell history / CI logs, not silently
            // hidden inside a TOML field.
            "--force-misconfig" => {
                force_misconfig = true;
            }
            arg if !arg.starts_with('-') && artifact_path.is_none() => {
                artifact_path = Some(PathBuf::from(arg));
            }
            other => return Err(CliError::Usage(format!("unknown policy sign flag: {other:?}"))),
        }
        i += 1;
    }

    let artifact_path = artifact_path
        .ok_or_else(|| CliError::Usage("policy sign requires <artifact.toml>".to_owned()))?;
    let key_path = key_path
        .or_else(|| flags.operator_key_path.clone())
        .ok_or_else(|| {
            CliError::Usage(
                "policy sign requires --key <path> or --operator-key global flag".to_owned(),
            )
        })?;

    // V2 hard-reject (plan-bundle-sealing.md §4.5): reject any attempt to
    // produce a V1-style sibling `plan.sig` for a `plan.toml` artifact.
    // `policy sign` remains the canonical signer for `policy.toml`,
    // delegation artifacts, and every other non-plan TOML, so the
    // narrowest reject we can make is to filter on the canonical
    // V1 plan filename. An operator who insists on signing a plan-shaped
    // artifact through this path would have to rename it, which is a
    // strong enough signal that they know they are leaving the V2 happy
    // path.
    //
    // The §4.5 migration guide tells operators their plan submission
    // path is `raxis submit plan <plan.toml>`, which signs in memory and
    // submits in the same IPC call — there is no on-disk `plan.sig`.
    if is_v1_plan_artifact_path(&artifact_path) {
        return Err(CliError::Usage(v1_plan_sign_removal_message(&artifact_path)));
    }

    // Read artifact bytes verbatim. Whitespace, BOM, trailing newline — the
    // signature is over the file as it sits on disk; the kernel will hash and
    // verify the same exact bytes.
    let artifact_bytes = fs::read(&artifact_path).map_err(|e| CliError::Io {
        path: artifact_path.display().to_string(),
        source: e,
    })?;

    // Step 7 (operator-cert ceremony) — refuse to sign a policy artifact
    // that opts into structural cert-misconfig bypass UNLESS the operator
    // explicitly passed `--force-misconfig`. We never block plan.toml or
    // any other artifact: the detector is intentionally conservative
    // (parses as a permissive TOML and only fires when there's at least
    // one operators.entries[*].force_misconfig_bypass = true).
    let bypass_entries = scan_for_misconfig_bypass(&artifact_bytes);
    if !bypass_entries.is_empty() && !force_misconfig {
        return Err(CliError::Usage(format!(
            "refusing to sign {}: {n} operator entr{ies_or_y} declare \
             force_misconfig_bypass = true (operators: {ops}). \
             Re-run with `--force-misconfig` to acknowledge the bypass; \
             the kernel will emit one OperatorCertMisconfigBypassed audit \
             event per relaxed structural rule at boot.",
            artifact_path.display(),
            n              = bypass_entries.len(),
            ies_or_y       = if bypass_entries.len() == 1 { "y" } else { "ies" },
            ops            = bypass_entries.join(", "),
        )));
    }
    if !bypass_entries.is_empty() {
        // --force-misconfig path: print a structured warning to stderr so
        // CI logs and shell scrollback both record the bypass at sign time.
        eprintln!(
            "{{\"level\":\"warn\",\"event\":\"policy_sign_misconfig_bypass\",\
             \"artifact\":\"{}\",\"bypassed_operators\":[{}]}}",
            artifact_path.display(),
            bypass_entries
                .iter()
                .map(|s| format!("\"{}\"", s.replace('"', "\\\"")))
                .collect::<Vec<_>>()
                .join(","),
        );
    }

    // Plain SHA-256 of the bytes (for `plan_sha256` field — surfaces in the
    // kernel's `signed_plan_artifacts.plan_bytes` and audit records).
    let sha256 = plan_artifact_sha256(&artifact_bytes);

    // Sign the canonical 32-byte SHA-256 of "RAXIS-V1-PLAN\x00" || artifact_bytes.
    // See module header — this MUST match what the kernel passes to
    // `Ed25519::verify` in `lifecycle::approve_plan`.
    let signing_key = crate::signing::load_operator_key(&key_path)?;
    let signing_input = plan_signing_input(&artifact_bytes);
    let sig_hex = crate::signing::sign_bytes(&signing_key, &signing_input);

    // Compute operator fingerprint.
    let pubkey_bytes = signing_key.verifying_key().to_bytes();
    let fingerprint = crate::conn::pubkey_fingerprint(&pubkey_bytes);

    // Write <artifact>.sig in TOML format.
    let sig_path = artifact_path.with_extension("sig");
    let sig_toml = format!(
        r#"# RAXIS artifact signature — generated by `raxis policy sign`
signed_by      = "{fingerprint}"
plan_sha256    = "{sha256}"
signature_hex  = "{sig_hex}"
signed_at      = {signed_at}
"#,
        signed_at = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs(),
    );
    fs::write(&sig_path, sig_toml.as_bytes()).map_err(|e| CliError::Io {
        path: sig_path.display().to_string(),
        source: e,
    })?;

    println!("✓ Signed {} → {}", artifact_path.display(), sig_path.display());
    println!("  fingerprint:  {fingerprint}");
    println!("  plan_sha256:  {sha256}");

    Ok(())
}

// ---------------------------------------------------------------------------
// V1 plan-signing reject — plan-bundle-sealing.md §4.5
// ---------------------------------------------------------------------------

/// Returns `true` when the file's basename is the V1 plan convention
/// (`plan.toml`). Comparison is case-sensitive — the V1 contract was
/// case-sensitive too (`signed_plan_artifacts` keys on the literal
/// bytes), and Linux/macOS filesystems are typically case-sensitive.
/// An operator who genuinely needs to sign a plan-shaped artifact
/// through `policy sign` can rename it to e.g. `Plan.toml`; the
/// rename is itself a strong signal that they understand they are
/// leaving the V2 happy path.
pub(crate) fn is_v1_plan_artifact_path(path: &std::path::Path) -> bool {
    path.file_name()
        .and_then(|n| n.to_str())
        .map(|name| name == "plan.toml")
        .unwrap_or(false)
}

/// Operator-facing migration text. Pulled out of `run_sign` so the test
/// suite can pin the exact message — drift here is operator-visible
/// behaviour change and forces a corresponding spec update in
/// `plan-bundle-sealing.md §4.5`.
pub(crate) fn v1_plan_sign_removal_message(artifact_path: &std::path::Path) -> String {
    format!(
        "V1 `policy sign {artifact}` (plan-signing path) is removed in V2.\n\
         \n\
         The two-step `policy sign plan.toml` + `plan submit <id> <dir>`\n\
         workflow is replaced by V2.1 atomic sign+submit:\n\
         \n\
         \traxis submit plan {artifact} [--initiative-id <id>] \\\n\
         \t                                       [--no-dry-run]\n\
         \n\
         The V2 path signs the canonical plan bundle in memory and ships\n\
         it to the kernel in a single IPC call — no on-disk `plan.sig`,\n\
         no TOCTOU between sign and submit. `policy sign` remains the\n\
         canonical signer for `policy.toml`, delegation artifacts, and\n\
         every other non-plan TOML. See plan-bundle-sealing.md §4 for\n\
         the full ceremony and §4.5 for the migration guide.",
        artifact = artifact_path.display(),
    )
}

// ---------------------------------------------------------------------------
// scan_for_misconfig_bypass — best-effort detector for the
// `--force-misconfig` gate.
//
// We intentionally do NOT route through `raxis-policy::PolicyBundle::validate`:
// validation does signature checks, fingerprint checks, and bundle-wide
// invariants that haven't been enforced yet at sign time (the operator
// may be mid-edit). We just want to know "does this artifact carry at
// least one operator entry with `force_misconfig_bypass = true`?" — a
// permissive serde shape over the few fields we care about gives us
// exactly that, with zero false positives on plan.toml / non-policy
// artifacts (which never carry `[[operators.entries]]`).
//
// Returns the display_names (or fingerprints, if display_name is missing)
// of every entry that opted into bypass, in declaration order. Empty
// vector means "no bypass detected" — caller proceeds normally.
// ---------------------------------------------------------------------------
fn scan_for_misconfig_bypass(artifact_bytes: &[u8]) -> Vec<String> {
    #[derive(serde::Deserialize)]
    struct Probe {
        #[serde(default)]
        operators: Option<OperatorsBlock>,
    }
    #[derive(serde::Deserialize)]
    struct OperatorsBlock {
        #[serde(default)]
        entries: Vec<OperatorEntryProbe>,
    }
    #[derive(serde::Deserialize)]
    struct OperatorEntryProbe {
        #[serde(default)]
        display_name: Option<String>,
        #[serde(default)]
        pubkey_fingerprint: Option<String>,
        #[serde(default)]
        force_misconfig_bypass: bool,
    }

    let s = match std::str::from_utf8(artifact_bytes) {
        Ok(s) => s,
        Err(_) => return Vec::new(),
    };
    let parsed: Probe = match toml::from_str(s) {
        Ok(p) => p,
        // Not parseable as TOML, or the shape doesn't match — treat as
        // not-a-policy. The downstream signing step still runs because the
        // signature is over raw bytes; we only block when we can prove the
        // artifact opted into bypass.
        Err(_) => return Vec::new(),
    };
    let entries = parsed.operators.map(|b| b.entries).unwrap_or_default();
    entries
        .into_iter()
        .filter(|e| e.force_misconfig_bypass)
        .map(|e| {
            e.display_name
                .or(e.pubkey_fingerprint)
                .unwrap_or_else(|| "<unnamed>".to_owned())
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Tests — `--force-misconfig` gate.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ----- V1 plan-signing reject (§4.5) ---------------------------------

    #[test]
    fn is_v1_plan_artifact_path_matches_canonical_filename() {
        assert!(is_v1_plan_artifact_path(std::path::Path::new("plan.toml")));
        assert!(is_v1_plan_artifact_path(std::path::Path::new("./plan.toml")));
        assert!(is_v1_plan_artifact_path(std::path::Path::new(
            "/tmp/initiatives/foo/plan.toml"
        )));
    }

    #[test]
    fn is_v1_plan_artifact_path_rejects_non_plan_toml_artifacts() {
        // policy.toml (the canonical use of `policy sign`) must NOT trip
        // the §4.5 hard-reject — the operator workflow for policy
        // signing is unchanged in V2.
        assert!(!is_v1_plan_artifact_path(std::path::Path::new(
            "policy.toml"
        )));
        assert!(!is_v1_plan_artifact_path(std::path::Path::new(
            "delegation.toml"
        )));
        // Case-sensitivity: a deliberately-renamed file is operator's
        // explicit choice and bypasses the safety net (see fn doc).
        assert!(!is_v1_plan_artifact_path(std::path::Path::new(
            "Plan.toml"
        )));
        assert!(!is_v1_plan_artifact_path(std::path::Path::new(
            "plan.json"
        )));
        // No filename component (e.g. directory path) → not a plan.
        assert!(!is_v1_plan_artifact_path(std::path::Path::new("/tmp/")));
    }

    #[test]
    fn v1_plan_sign_removal_message_mentions_v2_replacement_command() {
        // Pin the exact text so a future drift forces a spec update.
        // The hint MUST contain (a) the literal V2 invocation
        // `raxis submit plan`, (b) the reference to the `plan-bundle-
        // sealing.md` spec, (c) a clarifying mention that
        // `policy sign` is still the right tool for non-plan artifacts.
        let p = std::path::Path::new("/work/initiatives/foo/plan.toml");
        let msg = v1_plan_sign_removal_message(p);
        assert!(msg.contains("raxis submit plan"), "msg = {msg:?}");
        assert!(msg.contains("plan-bundle-sealing.md"), "msg = {msg:?}");
        assert!(msg.contains("`policy.toml`"), "msg = {msg:?}");
        // The operator's path appears verbatim so they can identify
        // which file the CLI is rejecting.
        assert!(
            msg.contains("/work/initiatives/foo/plan.toml"),
            "msg = {msg:?}",
        );
    }

    // ----- Original `--force-misconfig` gate tests ------------------------

    #[test]
    fn scan_returns_empty_for_a_plan_toml_without_operators() {
        // A plan.toml has no `[[operators.entries]]` block; the detector
        // must never flag it.
        let plan = br#"
[meta]
title = "demo plan"
[[tasks]]
task_id = "t1"
"#;
        assert!(scan_for_misconfig_bypass(plan).is_empty());
    }

    #[test]
    fn scan_returns_empty_when_no_entry_opts_into_bypass() {
        let policy = br#"
[meta]
epoch = 1
[[operators.entries]]
pubkey_fingerprint = "abcd1234abcd1234abcd1234abcd1234"
display_name       = "chika"
"#;
        assert!(scan_for_misconfig_bypass(policy).is_empty());
    }

    #[test]
    fn scan_lists_bypassed_entries_in_declaration_order() {
        // Two entries: chika does NOT bypass, jinanwa DOES. The detector must
        // surface only jinanwa, and surface him by display_name.
        let policy = br#"
[[operators.entries]]
pubkey_fingerprint = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
display_name       = "chika"
force_misconfig_bypass = false

[[operators.entries]]
pubkey_fingerprint = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
display_name       = "jinanwa"
force_misconfig_bypass = true
"#;
        assert_eq!(scan_for_misconfig_bypass(policy), vec!["jinanwa".to_owned()]);
    }

    #[test]
    fn scan_falls_back_to_fingerprint_when_display_name_missing() {
        // Defensive: if the operator omitted display_name on the bypass
        // entry, the warning still has to identify _which_ entry. Fall
        // back to the fingerprint so the operator can grep for it.
        let policy = br#"
[[operators.entries]]
pubkey_fingerprint = "ccccccccccccccccccccccccccccccccc"
force_misconfig_bypass = true
"#;
        assert_eq!(
            scan_for_misconfig_bypass(policy),
            vec!["ccccccccccccccccccccccccccccccccc".to_owned()]
        );
    }

    #[test]
    fn scan_returns_empty_for_non_utf8_bytes() {
        // Garbage bytes (e.g. a sliced binary file) must fail closed:
        // empty list ⇒ no block, signing proceeds. We never want
        // false positives on artifacts that aren't policies.
        let bytes = &[0xff_u8, 0xfe, 0x00, 0x80, 0xfe];
        assert!(scan_for_misconfig_bypass(bytes).is_empty());
    }

    #[test]
    fn scan_returns_empty_for_unparseable_toml() {
        assert!(scan_for_misconfig_bypass(b"not a valid = = = TOML").is_empty());
    }

    // ----- generate-sidecar-secret helpers (V2_GAPS §C5) -----------------

    #[test]
    fn hex_encode_round_trips_through_hex_crate() {
        let bytes = [0x00u8, 0x01, 0xff, 0xab, 0xcd, 0xef];
        let mine = hex_encode(&bytes);
        let theirs = hex::encode(bytes);
        assert_eq!(mine, theirs);
    }

    #[test]
    fn hex_encode_emits_exactly_2x_the_input_length() {
        let bytes = [0u8; 32];
        let h = hex_encode(&bytes);
        assert_eq!(h.len(), 64, "32-byte input must produce 64 hex chars");
        assert!(h.chars().all(|c| matches!(c, '0'..='9' | 'a'..='f')));
    }

    #[test]
    fn sidecar_secret_fingerprint_is_8_hex_chars() {
        let fp = sidecar_secret_fingerprint(
            "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
        );
        assert_eq!(fp.len(), 8);
        assert!(fp.chars().all(|c| matches!(c, '0'..='9' | 'a'..='f')));
    }

    #[test]
    fn sidecar_secret_fingerprint_is_deterministic() {
        let s = "feedfacecafebeefdeadbeefcafebabefeedfacecafebeefdeadbeefcafebabe";
        let a = sidecar_secret_fingerprint(s);
        let b = sidecar_secret_fingerprint(s);
        assert_eq!(a, b);
    }

    #[test]
    fn sidecar_secret_fingerprint_changes_with_input() {
        let a = sidecar_secret_fingerprint(&"a".repeat(64));
        let b = sidecar_secret_fingerprint(&"b".repeat(64));
        assert_ne!(a, b);
    }

    fn empty_flags() -> GlobalFlags {
        GlobalFlags {
            data_dir:          std::path::PathBuf::from("/tmp/raxis-test-data-dir"),
            socket_path:       None,
            operator_key_path: None,
        }
    }

    #[test]
    fn generate_sidecar_secret_rejects_unknown_flag() {
        let flags = empty_flags();
        let err = run_generate_sidecar_secret(&flags, &["--bogus".to_owned()])
            .expect_err("unknown flag must be a usage error");
        assert!(matches!(err, CliError::Usage(_)));
    }

    #[test]
    fn generate_sidecar_secret_rejects_json_and_annotated_together() {
        let flags = empty_flags();
        let err = run_generate_sidecar_secret(
            &flags,
            &["--json".to_owned(), "--annotated".to_owned()],
        )
        .expect_err("--json + --annotated must be a usage error");
        match err {
            CliError::Usage(m) => {
                assert!(m.contains("mutually exclusive"), "msg = {m:?}")
            }
            other => panic!("expected Usage, got {other:?}"),
        }
    }

    #[test]
    fn scan_handles_multiple_bypassed_entries() {
        let policy = br#"
[[operators.entries]]
pubkey_fingerprint = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
display_name = "chika"
force_misconfig_bypass = true

[[operators.entries]]
pubkey_fingerprint = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
display_name = "jinanwa"
force_misconfig_bypass = true
"#;
        assert_eq!(
            scan_for_misconfig_bypass(policy),
            vec!["chika".to_owned(), "jinanwa".to_owned()]
        );
    }
}
